=== xiaolizi521/xztech/old_dev/bleach7/Original/index.dtd
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Index [

<!ELEMENT Index (Donation, Releases)>
<!ELEMENT Donation (Current, Goal, Server, Media1, Media2, Month, Year, Donate)>
<!ELEMENT Current (#PCDATA)>
<!ELEMENT Goal (#PCDATA)>
<!ELEMENT Server (#PCDATA)>
<!ELEMENT Media1 (#PCDATA)>
<!ELEMENT Media2 (#PCDATA)>
<!ELEMENT Month (#PCDATA)>
<!ELEMENT Year (#PCDATA)>
<!ELEMENT Donate (Donator, Amount)*>
<!ELEMENT Donator (#PCDATA)>
<!ELEMENT Amount (#PCDATA)>
<!ELEMENT Releases (Anime, Manga)>
<!ELEMENT Anime (aRAW, aSUB)>
<!ELEMENT aRAW (#PCDATA)>
<!ELEMENT aSUB (#PCDATA)>
<!ELEMENT Manga (mRAW, mSUB)>
<!ELEMENT mRAW (#PCDATA)>
<!ELEMENT mSUB (#PCDATA)>
]>

=== xiaolizi521/xztech/old_dev/bleach7/Original/xml/index.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE Manga SYSTEM "./index.dtd">
<Index>
	<Donation>
		<Current>57</Current>
		<Goal>450</Goal>
		<Server>90</Server>
		<Media1>150</Media1>
		<Media2>150</Media2>
		<Month>7</Month>
		<Year>2006</Year>
		<Donate>
			<Donator>Anonamous</Donator>
			<Amount>57</Amount>
		</Donate>
	</Donation>
	<Releases>
		<Anime>
			<aRAW>89</aRAW>
			<aSUB>89</aSUB>
		</Anime>
		<Manga>
			<mRAW>236</mRAW>
			<mSUB>235</mSUB>
		</Manga>
	</Releases>
</Index>
